<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOmxcCjN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOmxcCjN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOmxcCjN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOmxcCjN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOmxcCjN\App_KernelDevDebugContainer([
    'container.build_hash' => 'OmxcCjN',
    'container.build_id' => '49fdaa69',
    'container.build_time' => 1586010614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOmxcCjN');
