<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgYqN17\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgYqN17/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQgYqN17.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQgYqN17\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQgYqN17\App_KernelDevDebugContainer([
    'container.build_hash' => 'QgYqN17',
    'container.build_id' => 'bd072000',
    'container.build_time' => 1586015554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgYqN17');
